// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once
#include "winrt/impl/Microsoft.AI.Skills.SkillInterfacePreview.0.h"
#include "winrt/impl/Windows.Media.0.h"
#include "winrt/impl/Windows.Foundation.0.h"
#include "winrt/impl/Microsoft.AI.Skills.Vision.ObjectDetectorPreview.0.h"

WINRT_EXPORT namespace winrt::Microsoft::AI::Skills::Vision::ObjectDetectorPreview {

struct WINRT_EBO IObjectDetectorBinding :
    Windows::Foundation::IInspectable,
    impl::consume_t<IObjectDetectorBinding>
{
    IObjectDetectorBinding(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IObjectDetectorDescription :
    Windows::Foundation::IInspectable,
    impl::consume_t<IObjectDetectorDescription>
{
    IObjectDetectorDescription(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IObjectDetectorResult :
    Windows::Foundation::IInspectable,
    impl::consume_t<IObjectDetectorResult>
{
    IObjectDetectorResult(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IObjectDetectorResultListDescriptorFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IObjectDetectorResultListDescriptorFactory>
{
    IObjectDetectorResultListDescriptorFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IObjectDetectorResultListValue :
    Windows::Foundation::IInspectable,
    impl::consume_t<IObjectDetectorResultListValue>
{
    IObjectDetectorResultListValue(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IObjectDetectorSkill :
    Windows::Foundation::IInspectable,
    impl::consume_t<IObjectDetectorSkill>
{
    IObjectDetectorSkill(std::nullptr_t = nullptr) noexcept {}
};

}
