// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once
#include "winrt/impl/Windows.Graphics.DirectX.Direct3D11.1.h"
#include "winrt/impl/Windows.Graphics.Imaging.1.h"
#include "winrt/impl/Windows.Media.1.h"
#include "winrt/impl/Windows.Foundation.1.h"
#include "winrt/impl/Windows.Foundation.Collections.1.h"
#include "winrt/impl/Microsoft.AI.Skills.SkillInterfacePreview.1.h"

WINRT_EXPORT namespace winrt::Microsoft::AI::Skills::SkillInterfacePreview {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::Microsoft::AI::Skills::SkillInterfacePreview {

struct WINRT_EBO SkillExecutionDeviceCPU :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillExecutionDeviceCPU,
    impl::require<SkillExecutionDeviceCPU, Microsoft::AI::Skills::SkillInterfacePreview::ISkillExecutionDevice>
{
    SkillExecutionDeviceCPU(std::nullptr_t) noexcept {}
    static Microsoft::AI::Skills::SkillInterfacePreview::SkillExecutionDeviceCPU Create();
};

struct WINRT_EBO SkillExecutionDeviceDirectX :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillExecutionDeviceDirectX,
    impl::require<SkillExecutionDeviceDirectX, Microsoft::AI::Skills::SkillInterfacePreview::ISkillExecutionDevice>
{
    SkillExecutionDeviceDirectX(std::nullptr_t) noexcept {}
    static Windows::Foundation::Collections::IVectorView<Microsoft::AI::Skills::SkillInterfacePreview::SkillExecutionDeviceDirectX> GetAvailableDirectXExecutionDevices();
    static Microsoft::AI::Skills::SkillInterfacePreview::SkillExecutionDeviceDirectX Create(Windows::Graphics::DirectX::Direct3D11::IDirect3DDevice const& direct3D11Device);
};

struct WINRT_EBO SkillFeature :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeature,
    impl::require<SkillFeature, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeature2, Windows::Foundation::IClosable>
{
    SkillFeature(std::nullptr_t) noexcept {}
    static Microsoft::AI::Skills::SkillInterfacePreview::SkillFeature Create(Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureDescriptor const& descriptor, Microsoft::AI::Skills::SkillInterfacePreview::ISkillExecutionDevice const& device);
};

struct WINRT_EBO SkillFeatureImageDescriptor :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureImageDescriptor,
    impl::require<SkillFeatureImageDescriptor, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureImageDescriptor2>
{
    SkillFeatureImageDescriptor(std::nullptr_t) noexcept {}
    SkillFeatureImageDescriptor(param::hstring const& name, param::hstring const& description, bool isRequired, int32_t width, int32_t height, int32_t maxDimension, Windows::Graphics::Imaging::BitmapPixelFormat const& supportedBitmapPixelFormat, Windows::Graphics::Imaging::BitmapAlphaMode const& supportedBitmapAlphaMode);
};

struct WINRT_EBO SkillFeatureImageValue :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureImageValue,
    impl::require<SkillFeatureImageValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureValue, Windows::Foundation::IClosable>
{
    SkillFeatureImageValue(std::nullptr_t) noexcept {}
};

struct WINRT_EBO SkillFeatureMapDescriptor :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureMapDescriptor,
    impl::require<SkillFeatureMapDescriptor, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureMapDescriptor2>
{
    SkillFeatureMapDescriptor(std::nullptr_t) noexcept {}
    SkillFeatureMapDescriptor(param::hstring const& name, param::hstring const& description, bool isRequired, Microsoft::AI::Skills::SkillInterfacePreview::SkillElementKind const& valueElementKind, Microsoft::AI::Skills::SkillInterfacePreview::SkillElementKind const& keyElementKind, param::iterable<Windows::Foundation::IInspectable> const& validKeys);
};

struct WINRT_EBO SkillFeatureMapValue :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureMapValue,
    impl::require<SkillFeatureMapValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureValue, Windows::Foundation::IClosable>
{
    SkillFeatureMapValue(std::nullptr_t) noexcept {}
};

struct WINRT_EBO SkillFeatureTensorBooleanValue :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorBooleanValue,
    impl::require<SkillFeatureTensorBooleanValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureValue, Windows::Foundation::IClosable>
{
    SkillFeatureTensorBooleanValue(std::nullptr_t) noexcept {}
};

struct WINRT_EBO SkillFeatureTensorDescriptor :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorDescriptor,
    impl::require<SkillFeatureTensorDescriptor, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorDescriptor2>
{
    SkillFeatureTensorDescriptor(std::nullptr_t) noexcept {}
    SkillFeatureTensorDescriptor(param::hstring const& name, param::hstring const& description, bool isRequired, param::vector_view<int64_t> const& shape, Microsoft::AI::Skills::SkillInterfacePreview::SkillElementKind const& elementKind);
};

struct WINRT_EBO SkillFeatureTensorDoubleValue :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorDoubleValue,
    impl::require<SkillFeatureTensorDoubleValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureValue, Windows::Foundation::IClosable>
{
    SkillFeatureTensorDoubleValue(std::nullptr_t) noexcept {}
};

struct WINRT_EBO SkillFeatureTensorFloat16Value :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorFloat16Value,
    impl::require<SkillFeatureTensorFloat16Value, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureValue, Windows::Foundation::IClosable>
{
    SkillFeatureTensorFloat16Value(std::nullptr_t) noexcept {}
};

struct WINRT_EBO SkillFeatureTensorFloatValue :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorFloatValue,
    impl::require<SkillFeatureTensorFloatValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureValue, Windows::Foundation::IClosable>
{
    SkillFeatureTensorFloatValue(std::nullptr_t) noexcept {}
};

struct WINRT_EBO SkillFeatureTensorInt16Value :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorInt16Value,
    impl::require<SkillFeatureTensorInt16Value, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureValue, Windows::Foundation::IClosable>
{
    SkillFeatureTensorInt16Value(std::nullptr_t) noexcept {}
};

struct WINRT_EBO SkillFeatureTensorInt64Value :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorInt64Value,
    impl::require<SkillFeatureTensorInt64Value, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureValue, Windows::Foundation::IClosable>
{
    SkillFeatureTensorInt64Value(std::nullptr_t) noexcept {}
};

struct WINRT_EBO SkillFeatureTensorInt8Value :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorInt8Value,
    impl::require<SkillFeatureTensorInt8Value, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureValue, Windows::Foundation::IClosable>
{
    SkillFeatureTensorInt8Value(std::nullptr_t) noexcept {}
};

struct WINRT_EBO SkillFeatureTensorIntValue :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorIntValue,
    impl::require<SkillFeatureTensorIntValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureValue, Windows::Foundation::IClosable>
{
    SkillFeatureTensorIntValue(std::nullptr_t) noexcept {}
};

struct WINRT_EBO SkillFeatureTensorStringValue :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorStringValue,
    impl::require<SkillFeatureTensorStringValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureValue, Windows::Foundation::IClosable>
{
    SkillFeatureTensorStringValue(std::nullptr_t) noexcept {}
};

struct WINRT_EBO SkillFeatureTensorUInt16Value :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorUInt16Value,
    impl::require<SkillFeatureTensorUInt16Value, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureValue, Windows::Foundation::IClosable>
{
    SkillFeatureTensorUInt16Value(std::nullptr_t) noexcept {}
};

struct WINRT_EBO SkillFeatureTensorUInt32Value :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorUInt32Value,
    impl::require<SkillFeatureTensorUInt32Value, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureValue, Windows::Foundation::IClosable>
{
    SkillFeatureTensorUInt32Value(std::nullptr_t) noexcept {}
};

struct WINRT_EBO SkillFeatureTensorUInt64Value :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorUInt64Value,
    impl::require<SkillFeatureTensorUInt64Value, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureValue, Windows::Foundation::IClosable>
{
    SkillFeatureTensorUInt64Value(std::nullptr_t) noexcept {}
};

struct WINRT_EBO SkillFeatureTensorUInt8Value :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorUInt8Value,
    impl::require<SkillFeatureTensorUInt8Value, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureTensorValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureValue, Windows::Foundation::IClosable>
{
    SkillFeatureTensorUInt8Value(std::nullptr_t) noexcept {}
};

struct WINRT_EBO SkillVersion :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillVersion
{
    SkillVersion(std::nullptr_t) noexcept {}
    static Microsoft::AI::Skills::SkillInterfacePreview::SkillVersion Create(uint16_t major, uint16_t minor, param::hstring const& author, param::hstring const& publisher);
};

struct WINRT_EBO VisionSkillBindingHelper :
    Microsoft::AI::Skills::SkillInterfacePreview::IVisionSkillBindingHelper,
    impl::require<VisionSkillBindingHelper, Microsoft::AI::Skills::SkillInterfacePreview::IVisionSkillBindingHelperOverrides, Windows::Foundation::Collections::IIterable<Windows::Foundation::Collections::IKeyValuePair<hstring, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeature>>, Windows::Foundation::Collections::IMap<hstring, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeature>>
{
    VisionSkillBindingHelper(std::nullptr_t) noexcept {}
    VisionSkillBindingHelper(Microsoft::AI::Skills::SkillInterfacePreview::ISkillDescriptor const& descriptor, Microsoft::AI::Skills::SkillInterfacePreview::ISkillExecutionDevice const& device);
};

template <typename D>
class IVisionSkillBindingHelperOverridesT
{
    D& shim() noexcept { return *static_cast<D*>(this); }
    D const& shim() const noexcept { return *static_cast<const D*>(this); }

public:

    using IVisionSkillBindingHelperOverrides = winrt::Microsoft::AI::Skills::SkillInterfacePreview::IVisionSkillBindingHelperOverrides;

    Windows::Foundation::IAsyncAction SetInputImageInternalAsync(Windows::Media::VideoFrame const& videoFrame) const;
};

}
