// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once
#include "winrt/impl/Windows.Graphics.DirectX.Direct3D11.0.h"
#include "winrt/impl/Windows.Graphics.Imaging.0.h"
#include "winrt/impl/Windows.Media.0.h"
#include "winrt/impl/Windows.Foundation.0.h"
#include "winrt/impl/Windows.Foundation.Collections.0.h"
#include "winrt/impl/Microsoft.AI.Skills.SkillInterfacePreview.0.h"

WINRT_EXPORT namespace winrt::Microsoft::AI::Skills::SkillInterfacePreview {

struct WINRT_EBO ISkill :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkill>
{
    ISkill(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillBinding :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillBinding>,
    impl::require<ISkillBinding, Windows::Foundation::Collections::IIterable<Windows::Foundation::Collections::IKeyValuePair<hstring, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeature>>, Windows::Foundation::Collections::IMapView<hstring, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeature>>
{
    ISkillBinding(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillDescriptor :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillDescriptor>
{
    ISkillDescriptor(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillExecutionDevice :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillExecutionDevice>
{
    ISkillExecutionDevice(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillExecutionDeviceCPU :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillExecutionDeviceCPU>
{
    ISkillExecutionDeviceCPU(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillExecutionDeviceDirectX :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillExecutionDeviceDirectX>
{
    ISkillExecutionDeviceDirectX(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeature :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeature>
{
    ISkillFeature(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeature2 :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeature2>
{
    ISkillFeature2(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureDescriptor :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureDescriptor>
{
    ISkillFeatureDescriptor(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureImageDescriptor :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureImageDescriptor>,
    impl::require<ISkillFeatureImageDescriptor, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureDescriptor>
{
    ISkillFeatureImageDescriptor(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureImageDescriptor2 :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureImageDescriptor2>
{
    ISkillFeatureImageDescriptor2(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureImageDescriptorFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureImageDescriptorFactory>
{
    ISkillFeatureImageDescriptorFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureImageDescriptorStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureImageDescriptorStatics>
{
    ISkillFeatureImageDescriptorStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureImageValue :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureImageValue>
{
    ISkillFeatureImageValue(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureMapDescriptor :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureMapDescriptor>,
    impl::require<ISkillFeatureMapDescriptor, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureDescriptor>
{
    ISkillFeatureMapDescriptor(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureMapDescriptor2 :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureMapDescriptor2>
{
    ISkillFeatureMapDescriptor2(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureMapDescriptorFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureMapDescriptorFactory>
{
    ISkillFeatureMapDescriptorFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureMapDescriptorStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureMapDescriptorStatics>
{
    ISkillFeatureMapDescriptorStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureMapValue :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureMapValue>
{
    ISkillFeatureMapValue(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureStatics>
{
    ISkillFeatureStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureTensorBooleanValue :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureTensorBooleanValue>
{
    ISkillFeatureTensorBooleanValue(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureTensorDescriptor :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureTensorDescriptor>,
    impl::require<ISkillFeatureTensorDescriptor, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureDescriptor>
{
    ISkillFeatureTensorDescriptor(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureTensorDescriptor2 :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureTensorDescriptor2>
{
    ISkillFeatureTensorDescriptor2(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureTensorDescriptorFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureTensorDescriptorFactory>
{
    ISkillFeatureTensorDescriptorFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureTensorDescriptorStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureTensorDescriptorStatics>
{
    ISkillFeatureTensorDescriptorStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureTensorDoubleValue :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureTensorDoubleValue>
{
    ISkillFeatureTensorDoubleValue(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureTensorFloat16Value :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureTensorFloat16Value>
{
    ISkillFeatureTensorFloat16Value(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureTensorFloatValue :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureTensorFloatValue>
{
    ISkillFeatureTensorFloatValue(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureTensorInt16Value :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureTensorInt16Value>
{
    ISkillFeatureTensorInt16Value(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureTensorInt64Value :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureTensorInt64Value>
{
    ISkillFeatureTensorInt64Value(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureTensorInt8Value :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureTensorInt8Value>
{
    ISkillFeatureTensorInt8Value(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureTensorIntValue :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureTensorIntValue>
{
    ISkillFeatureTensorIntValue(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureTensorStringValue :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureTensorStringValue>
{
    ISkillFeatureTensorStringValue(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureTensorUInt16Value :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureTensorUInt16Value>
{
    ISkillFeatureTensorUInt16Value(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureTensorUInt32Value :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureTensorUInt32Value>
{
    ISkillFeatureTensorUInt32Value(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureTensorUInt64Value :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureTensorUInt64Value>
{
    ISkillFeatureTensorUInt64Value(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureTensorUInt8Value :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureTensorUInt8Value>
{
    ISkillFeatureTensorUInt8Value(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureTensorValue :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureTensorValue>,
    impl::require<ISkillFeatureTensorValue, Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureValue>
{
    ISkillFeatureTensorValue(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillFeatureValue :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillFeatureValue>
{
    ISkillFeatureValue(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillVersion :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillVersion>
{
    ISkillVersion(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISkillVersionStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISkillVersionStatics>
{
    ISkillVersionStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IVisionSkillBindingHelper :
    Windows::Foundation::IInspectable,
    impl::consume_t<IVisionSkillBindingHelper>
{
    IVisionSkillBindingHelper(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IVisionSkillBindingHelperFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IVisionSkillBindingHelperFactory>
{
    IVisionSkillBindingHelperFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IVisionSkillBindingHelperOverrides :
    Windows::Foundation::IInspectable,
    impl::consume_t<IVisionSkillBindingHelperOverrides>
{
    IVisionSkillBindingHelperOverrides(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO SkillExecutionDeviceCPUStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<SkillExecutionDeviceCPUStatics>
{
    SkillExecutionDeviceCPUStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO SkillExecutionDeviceDirectXStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<SkillExecutionDeviceDirectXStatics>
{
    SkillExecutionDeviceDirectXStatics(std::nullptr_t = nullptr) noexcept {}
};

}
