// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once
#include "winrt/impl/Microsoft.AI.Skills.SkillInterfacePreview.1.h"
#include "winrt/impl/Windows.Media.1.h"
#include "winrt/impl/Windows.Foundation.1.h"
#include "winrt/impl/Microsoft.AI.Skills.Vision.ObjectDetectorPreview.1.h"

WINRT_EXPORT namespace winrt::Microsoft::AI::Skills::Vision::ObjectDetectorPreview {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::Microsoft::AI::Skills::Vision::ObjectDetectorPreview {

struct WINRT_EBO ObjectDetectorBinding :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillBinding,
    impl::require<ObjectDetectorBinding, Microsoft::AI::Skills::Vision::ObjectDetectorPreview::IObjectDetectorBinding>
{
    ObjectDetectorBinding(std::nullptr_t) noexcept {}
};

struct WINRT_EBO ObjectDetectorDescriptor :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillDescriptor,
    impl::require<ObjectDetectorDescriptor, Microsoft::AI::Skills::Vision::ObjectDetectorPreview::IObjectDetectorDescription>
{
    ObjectDetectorDescriptor(std::nullptr_t) noexcept {}
    ObjectDetectorDescriptor();
};

struct WINRT_EBO ObjectDetectorResult :
    Microsoft::AI::Skills::Vision::ObjectDetectorPreview::IObjectDetectorResult
{
    ObjectDetectorResult(std::nullptr_t) noexcept {}
};

struct WINRT_EBO ObjectDetectorResultListDescriptor :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureDescriptor
{
    ObjectDetectorResultListDescriptor(std::nullptr_t) noexcept {}
    ObjectDetectorResultListDescriptor(param::hstring const& name, param::hstring const& description, bool isRequired);
};

struct WINRT_EBO ObjectDetectorResultListValue :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkillFeatureValue,
    impl::require<ObjectDetectorResultListValue, Microsoft::AI::Skills::Vision::ObjectDetectorPreview::IObjectDetectorResultListValue, Windows::Foundation::IClosable>
{
    ObjectDetectorResultListValue(std::nullptr_t) noexcept {}
};

struct WINRT_EBO ObjectDetectorSkill :
    Microsoft::AI::Skills::SkillInterfacePreview::ISkill,
    impl::require<ObjectDetectorSkill, Microsoft::AI::Skills::Vision::ObjectDetectorPreview::IObjectDetectorSkill, Windows::Foundation::IClosable>
{
    ObjectDetectorSkill(std::nullptr_t) noexcept {}
};

}
